package demo.model;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 03 15:33:20 CEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        NameJob,
        LevelJob,
        SequenzaJob;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int NAMEJOB = AttributesEnum.NameJob.index();
    public static final int LEVELJOB = AttributesEnum.LevelJob.index();
    public static final int SEQUENZAJOB = AttributesEnum.SequenzaJob.index();

    /**
     * This is the default constructor (do not remove).
     */
    public JobImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("demo.model.Job");
    }


    /**
     * Gets the attribute value for NameJob, using the alias name NameJob.
     * @return the value of NameJob
     */
    public String getNameJob() {
        return (String) getAttributeInternal(NAMEJOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for NameJob.
     * @param value value to set the NameJob
     */
    public void setNameJob(String value) {
        setAttributeInternal(NAMEJOB, value);
    }

    /**
     * Gets the attribute value for LevelJob, using the alias name LevelJob.
     * @return the value of LevelJob
     */
    public BigDecimal getLevelJob() {
        return (BigDecimal) getAttributeInternal(LEVELJOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for LevelJob.
     * @param value value to set the LevelJob
     */
    public void setLevelJob(BigDecimal value) {
        setAttributeInternal(LEVELJOB, value);
    }

    /**
     * Gets the attribute value for SequenzaJob, using the alias name SequenzaJob.
     * @return the value of SequenzaJob
     */
    public DBSequence getSequenzaJob() {
        return (DBSequence) getAttributeInternal(SEQUENZAJOB);
    }

    /**
     * @param sequenzaJob key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence sequenzaJob) {
        return new Key(new Object[] { sequenzaJob });
    }


}

