package demo.model.common;

import java.util.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 04 11:06:14 CEST 2023
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void createRow(String idDepartment, String nameDepartment, Date fromDate, Date toDate);

    void updateRowby_EFFDT_UPDATE_MODE(String idDepartment, String nameDepartment, Date effectiveDate);

    void updateRowby_EFFDT_UPDATE_CORRECTION(String idDepartment, String nameDepartment, Date effectiveDate);

    void deleteRow(String idDepartment);

    void updateRow(String idDepartment, String nameDepartment);
}

